## What working with R looks like {#part1_2}

We work with R in an interactive way. The R software itself is often associated with a console that has a blinking cursor used to enter commands and read results.

We wanted to reflect this work style in this book, which is why we present sample code alongside the output generated by the software. Both R instructions and their results are presented against a grey background so that you can find them quickly. Results are presented on lines that start with a double hash sign (##).

For example, the `substr()` function cuts out a substring with the coordinates provided in the parentheses. When you run the R software, you only need to type the instruction below to see the result in the same console window. Here, the result will be a string containing a single `R` letter.

```{r}
substr("What is supeR?", start = 13, stop = 13)
```

When we write about functions, packages, and language elements, we use a `fixed-width font`. Some key English terms are written in italics. When we first mention a function name from an untypical package, we mention the package name.

The `ggplot2::qplot()` notation signifies function `qplot()` in the `ggplot2` package. Sometimes, there are multiple functions in different packages that have the same name. In this case, we can precisely specify the function by providing the name of the package in front of it. When we need to install or turn on an uncommon package to use a given function, it is better to know which package offers the given function. At the end of this book, there is an index of functions – they are presented both alphabetically and by packages.

### Example: Poland in the FIFA ranking {#part_121}

Let us find out what “serious” work with R looks like based on the example below.

 * We will use some functions from the `rvest` package to directly read Poland’s FIFA rank from Wikipedia.
 
 * We will use some functions from the `tidyr` and `dplyr` packages to transform the data into the appropriate form.
 
 * We will use some functions from the `ggplot2` package to graphically present the data.
 
The entire R code which deals with those 3 stages is quite short and easy to analyse in a step-by-step manner. Some elements may seem familiar while others will appear surprising. We will explain the meaning of each element in subsequent sections.

> All R instructions contained in this book can be downloaded from [http://biecek.pl/R](http://biecek.pl/R).
The R instructions provided will always yield the same results. The only exception from this rule are some plots that have been modified to increase their readability in print.

#### Loading data {#part_1211}

The code snippet below loads a data table from the Polish version of *Poland national football team* available on Wikipedia. We used `rvest`, a package which is very useful for downloading data from websites.

There are multiple tables on the site we are interested in. We get them all, and then choose the one with 14 columns. Having loaded the data, we show the first 6 rows.

```
library("rvest")
wikiPL <- "https://pl.wikipedia.org/wiki/Reprezentacja_Polski_w_piłce_nożnej_mężczyzn"
webpage <- read_html(wikiPL)
table_links <- html_nodes(webpage, '.wikitable')
tables <- html_table(table_links, fill=TRUE)
FIFA_table <- which(sapply(tables, ncol) == 14)
tab <- tables[[FIFA_table]]
head(tab)
```

#### Data transformation {#part_1212}

Another step after loading the data is cleaning and transforming it. To that end, we can use functions from the `tidyr` and `dplyr` packages. We will explain them in detail shortly. For the time being, we will provide an abbreviated explanation.

We change the data from the wide format, in which months are stored in different columns, into the narrow format, where all months are stored in a single column. Then, we change Roman numerals used for months into Arabic numerals. At this point, our data is ready to be presented graphically.

```
library("tidyr")
library("dplyr")
colnames(tab)[2:13] <- 1:12
data_long <- gather(tab[,1:13], Month, Rank, -Year)
data_long <- mutate(data_long,
                    Position = as.numeric(Position),
                    Month = as.numeric(Month))
head(data_long, 3)
```

#### Graphical data presentation {#part_1213}

Now that we have loaded the data, it is time we looked at it. We can use the `ggplot2` package for graphical presentation purposes. Below, we present instructions that will generate the chart visible in Figure 1.3, which is called a box plot. It presents the minimal, maximal, mid-range and interquartile rank of Poland in each year of the ranking. We can see when the most prominent changes took place and when Poland reached its best ranks.

```
library("ggplot2")
ggplot(data_long, aes(factor(Year), Rank)) +
geom_boxplot() + ggtitle("Rank of Poland in FIFA Ranking")
```
